language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

sudo: false

script:
- mvn cobertura:cobertura

after_success:
- mvn cobertura:cobertura coveralls:report

branches:
  only:
  - master
  - stable
  - develop
