language: java

jdk:
  - oraclejdk9

cache:
  directories:
  - $HOME/.m2

sudo: false

script:
- mvn cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn cobertura:cobertura coveralls:report

branches:
  only:
  - master
  - stable
  - develop
