language: java

jdk:
  - openjdk11
  - openjdk12

os:
  - linux

sudo: false

cache:
  directories:
  - "$HOME/.m2"

before_cache:
- rm -rf $HOME/.m2/repository/com/opipo/terra-incognita-server

before_install:
- sudo apt-get install jq
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar http://central.maven.org/maven2/com/codacy/codacy-coverage-reporter/5.0.310/codacy-coverage-reporter-5.0.310.jar

after_success:
- java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/jacoco/jacoco.xml
- mvn clean test jacoco:report coveralls:report --quiet

branches:
  only:
  - master
  - stable
  - develop
