spring:
    data:
        mongodb:
            uri: mongodb://root:albertinizao@ds135039.mlab.com:35039/heroku_hsfl8dx3

user: ultimategamerating@gmail.com

token:
secret: 9SyECk96oDsTmXfogIieDI0cD/8FpnojlYSUJT5U9I/FGVmBz5oskmjOR8cbXTvoPjX+Pq/T/b1PqpHX0lYm0oCBjXWICA==