package com.opipo.terraincognitaserver.dto;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("EventInscriptionId autogenerated")
public class EventInscriptionIdTest {

    private EventInscriptionId eventInscriptionId;

    @BeforeEach
    public void init() {
        eventInscriptionId = new EventInscriptionId();
    }

    @Test
    @DisplayName("The getter and the setter of username work well")
    public void usernameAttributeTest() {
        String username = Integer.toString(1);
        eventInscriptionId.setUsername(username);
        assertEquals(username, eventInscriptionId.getUsername());
    }

    @Test
    @DisplayName("The getter and the setter of event work well")
    public void eventAttributeTest() {
        String event = Integer.toString(2);
        eventInscriptionId.setEvent(event);
        assertEquals(event, eventInscriptionId.getEvent());
    }

    @Test
    public void givenSameObjReturnThatTheyAreEquals() {
        EventInscriptionId o1 = new EventInscriptionId();
        EventInscriptionId o2 = new EventInscriptionId();
        assertEquals(o1, o2);
    }

    @Test
    public void givenSameObjReturnZero() {
        EventInscriptionId o1 = new EventInscriptionId();
        EventInscriptionId o2 = new EventInscriptionId();
        assertEquals(0, o1.compareTo(o2));
    }

    @Test
    public void givenObjectFromOtherClassReturnThatTheyArentEquals() {
        EventInscriptionId o1 = new EventInscriptionId();
        assertNotEquals(o1, new String());
    }

    @Test
    public void givenSameObjReturnSameHashCode() {
        EventInscriptionId o1 = new EventInscriptionId();
        EventInscriptionId o2 = new EventInscriptionId();
        assertEquals(o1.hashCode(), o2.hashCode());
    }

}