package com.opipo.terraincognitaserver.dto;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("InstalmentPrice autogenerated")
public class InstalmentPriceTest {

    private InstalmentPrice instalmentPrice;

    @BeforeEach
    public void init() {
        instalmentPrice = new InstalmentPrice();
    }

    @Test
    @DisplayName("The getter and the setter of percent work well")
    public void percentAttributeTest() {
        Double percent = Double.valueOf(1D);
        instalmentPrice.setPercent(percent);
        assertEquals(percent, instalmentPrice.getPercent());
    }

    @Test
    @DisplayName("The getter and the setter of lastDate work well")
    public void lastDateAttributeTest() {
        Long lastDate = Long.valueOf(1L);
        instalmentPrice.setLastDate(lastDate);
        assertEquals(lastDate, instalmentPrice.getLastDate());
    }

    @Test
    public void givenSameObjReturnThatTheyAreEquals() {
        InstalmentPrice o1 = new InstalmentPrice();
        InstalmentPrice o2 = new InstalmentPrice();
        assertEquals(o1, o2);
    }

    @Test
    public void givenSameObjReturnZero() {
        InstalmentPrice o1 = new InstalmentPrice();
        InstalmentPrice o2 = new InstalmentPrice();
        assertEquals(0, o1.compareTo(o2));
    }

    @Test
    public void givenObjectFromOtherClassReturnThatTheyArentEquals() {
        InstalmentPrice o1 = new InstalmentPrice();
        assertNotEquals(o1, "");
    }

    @Test
    public void givenSameObjReturnSameHashCode() {
        InstalmentPrice o1 = new InstalmentPrice();
        InstalmentPrice o2 = new InstalmentPrice();
        assertEquals(o1.hashCode(), o2.hashCode());
    }

}