package com.opipo.terraincognitaserver.dto;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("Price autogenerated")
public class PriceTest {

    private Price price;

    @BeforeEach
    public void init() {
        price = new Price();
    }

    @Test
    @DisplayName("The getter and the setter of totalPrice work well")
    public void totalPriceAttributeTest() {
        Double totalPrice = Double.valueOf(1D);
        price.setTotalPrice(totalPrice);
        assertEquals(totalPrice, price.getTotalPrice());
    }

    @Test
    @DisplayName("The getter and the setter of partnerDiscount work well")
    public void partnerDiscountAttributeTest() {
        Double partnerDiscount = Double.valueOf(2D);
        price.setPartnerDiscount(partnerDiscount);
        assertEquals(partnerDiscount, price.getPartnerDiscount());
    }

    @Test
    @DisplayName("The getter and the setter of npcDiscount work well")
    public void npcDiscountAttributeTest() {
        Double npcDiscount = Double.valueOf(3D);
        price.setNpcDiscount(npcDiscount);
        assertEquals(npcDiscount, price.getNpcDiscount());
    }

    @Test
    @DisplayName("The getter and the setter of inscriptionPrice work well")
    public void inscriptionPriceAttributeTest() {
        Double inscriptionPrice = Double.valueOf(4D);
        price.setInscriptionPrice(inscriptionPrice);
        assertEquals(inscriptionPrice, price.getInscriptionPrice());
    }

    @Test
    @DisplayName("The getter and the setter of inscriptionLastDate work well")
    public void inscriptionLastDateAttributeTest() {
        Long inscriptionLastDate = Long.valueOf(1L);
        price.setInscriptionLastDate(inscriptionLastDate);
        assertEquals(inscriptionLastDate, price.getInscriptionLastDate());
    }

    @Test
    @DisplayName("The getter and the setter of instalementPrices work well")
    public void instalementPricesAttributeTest() {
        List<InstalmentPrice> instalementPrices = new ArrayList<InstalmentPrice>();
        price.setInstalementPrices(instalementPrices);
        assertEquals(instalementPrices, price.getInstalementPrices());
    }

    @Test
    public void givenSameObjReturnThatTheyAreEquals() {
        Price o1 = new Price();
        Price o2 = new Price();
        assertEquals(o1, o2);
    }

    @Test
    public void givenSameObjReturnZero() {
        Price o1 = new Price();
        Price o2 = new Price();
        assertEquals(0, o1.compareTo(o2));
    }

    @Test
    public void givenObjectFromOtherClassReturnThatTheyArentEquals() {
        Price o1 = new Price();
        assertNotEquals(o1, new String());
    }

    @Test
    public void givenSameObjReturnSameHashCode() {
        Price o1 = new Price();
        Price o2 = new Price();
        assertEquals(o1.hashCode(), o2.hashCode());
    }

}