package com.opipo.terraincognitaserver.dto;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("Role autogenerated")
public class RoleTest {

    private Role role;

    @BeforeEach
    public void init() {
        role = new Role();
    }

    @Test
    @DisplayName("The getter and the setter of name work well")
    public void nameAttributeTest() {
        String name = Integer.toString(1);
        role.setName(name);
        assertEquals(name, role.getName());
    }

    @Test
    @DisplayName("The getter and the setter of description work well")
    public void descriptionAttributeTest() {
        String description = Integer.toString(2);
        role.setDescription(description);
        assertEquals(description, role.getDescription());
    }

    @Test
    public void givenSameObjReturnThatTheyAreEquals() {
        Role o1 = new Role();
        Role o2 = new Role();
        assertEquals(o1, o2);
    }

    @Test
    public void givenSameObjReturnZero() {
        Role o1 = new Role();
        Role o2 = new Role();
        assertEquals(0, o1.compareTo(o2));
    }

    @Test
    public void givenObjectFromOtherClassReturnThatTheyArentEquals() {
        Role o1 = new Role();
        assertNotEquals(o1, "");
    }

    @Test
    public void givenSameObjReturnSameHashCode() {
        Role o1 = new Role();
        Role o2 = new Role();
        assertEquals(o1.hashCode(), o2.hashCode());
    }

}