package com.opipo.terraincognitaserver.dto;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("SequenceId autogenerated")
public class SequenceIdTest {

    private SequenceId sequenceId;

    @BeforeEach
    public void init() {
        sequenceId = new SequenceId();
    }

    @Test
    @DisplayName("The getter and the setter of id work well")
    public void idAttributeTest() {
        String id = Integer.toString(1);
        sequenceId.setId(id);
        assertEquals(id, sequenceId.getId());
    }

    @Test
    @DisplayName("The getter and the setter of seq work well")
    public void seqAttributeTest() {
        long seq = Long.valueOf(1L);
        sequenceId.setSeq(seq);
        assertEquals(seq, sequenceId.getSeq());
    }

    @Test
    public void givenSameObjReturnThatTheyAreEquals() {
        SequenceId o1 = new SequenceId();
        SequenceId o2 = new SequenceId();
        assertEquals(o1, o2);
    }

    @Test
    public void givenSameObjReturnZero() {
        SequenceId o1 = new SequenceId();
        SequenceId o2 = new SequenceId();
        assertEquals(0, o1.compareTo(o2));
    }

    @Test
    public void givenObjectFromOtherClassReturnThatTheyArentEquals() {
        SequenceId o1 = new SequenceId();
        assertNotEquals(o1, "");
    }

    @Test
    public void givenSameObjReturnSameHashCode() {
        SequenceId o1 = new SequenceId();
        SequenceId o2 = new SequenceId();
        assertEquals(o1.hashCode(), o2.hashCode());
    }

}