package com.opipo.terraincognitaserver.dto;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("User autogenerated")
public class UserTest {

    private User user;

    @BeforeEach
    public void init() {
        user = new User();
    }

    @Test
    @DisplayName("The getter and the setter of username work well")
    public void usernameAttributeTest() {
        String username = Integer.toString(1);
        user.setUsername(username);
        assertEquals(username, user.getUsername());
    }

    @Test
    @DisplayName("The getter and the setter of password work well")
    public void passwordAttributeTest() {
        String password = Integer.toString(2);
        user.setPassword(password);
        assertEquals(password, user.getPassword());
    }

    @Test
    @DisplayName("The getter and the setter of name work well")
    public void nameAttributeTest() {
        String name = Integer.toString(3);
        user.setName(name);
        assertEquals(name, user.getName());
    }

    @Test
    @DisplayName("The getter and the setter of surname work well")
    public void surnameAttributeTest() {
        String surname = Integer.toString(4);
        user.setSurname(surname);
        assertEquals(surname, user.getSurname());
    }

    @Test
    @DisplayName("The getter and the setter of dni work well")
    public void dniAttributeTest() {
        String dni = Integer.toString(5);
        user.setDni(dni);
        assertEquals(dni, user.getDni());
    }

    @Test
    @DisplayName("The getter and the setter of email work well")
    public void emailAttributeTest() {
        String email = Integer.toString(6);
        user.setEmail(email);
        assertEquals(email, user.getEmail());
    }

    @Test
    @DisplayName("The getter and the setter of phone work well")
    public void phoneAttributeTest() {
        String phone = Integer.toString(7);
        user.setPhone(phone);
        assertEquals(phone, user.getPhone());
    }

    @Test
    @DisplayName("The getter and the setter of birthDate work well")
    public void birthDateAttributeTest() {
        Long birthDate = Long.valueOf(1L);
        user.setBirthDate(birthDate);
        assertEquals(birthDate, user.getBirthDate());
    }

    @Test
    @DisplayName("The getter and the setter of medicalInformation work well")
    public void medicalInformationAttributeTest() {
        String medicalInformation = Integer.toString(8);
        user.setMedicalInformation(medicalInformation);
        assertEquals(medicalInformation, user.getMedicalInformation());
    }

    @Test
    public void givenSameObjReturnThatTheyAreEquals() {
        User o1 = new User();
        User o2 = new User();
        assertEquals(o1, o2);
    }

    @Test
    public void givenSameObjReturnZero() {
        User o1 = new User();
        User o2 = new User();
        assertEquals(0, o1.compareTo(o2));
    }

    @Test
    public void givenObjectFromOtherClassReturnThatTheyArentEquals() {
        User o1 = new User();
        assertNotEquals(o1, "");
    }

    @Test
    public void givenSameObjReturnSameHashCode() {
        User o1 = new User();
        User o2 = new User();
        assertEquals(o1.hashCode(), o2.hashCode());
    }

}